#!/bin/bash
#
### BEGIN INIT INFO
# Provides: $kafka-server
# Default-Start: 3 4 5
# Default-Stop: 0 1 6
### END INIT INFO

# Source function library.
. /etc/init.d/functions
RETVAL=0

STORM_USER=kafka
PID_FILE="/var/run/kafka-server/kafka-server.pid"

KAFKA_HOME="/opt/kafka-server"
KAFKA_LIB="$KAFKA_HOME/lib"
KAFKA_CONF="$KAFKA_HOME/conf"

# Source config
. /etc/sysconfig/kafka-server

start() {
    if kakfa_status>/dev/null; then
    	echo "Kafka server is already running."
    	exit 1
    else
    	echo "Starting kafka server..."
    fi 
    STORM_CMD="java -$JVM_TYPE -Xmx$SUPERVISOR_JVM_MEMORY -Duser.dir=\"$STORM_HOME\" -Djava.library.path=\"$JAVA_LIBRARY_PATH\" -Dstorm.options=\"$STORM_OPTIONS\" -Dstorm.home=\"$STORM_HOME\" -Dlogfile.name=supervisor.log $SUPERVISOR_JVM_OPTS -cp \"$CLASSPATH\" backtype.storm.daemon.supervisor &"
    runuser --shell=/bin/bash --preserve-environment $STORM_USER --command="$STORM_CMD > /dev/null && echo \$! > $PID_FILE"
    RETVAL=$?
    kakfa_status
    return $RETVAL
}

stop() {
    if kakfa_status; then
        echo "Stopping kafka server..."
        killproc -p $PID_FILE -TERM
        RETVAL=$?
        kakfa_status
    else
        return 0
    fi
    return $RETVAL
}

kakfa_status() {
    status -p $PID_FILE kafka-server
    return $?
}

restart() {
        stop
        start
}

reload()  {
    restart
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        kakfa_status
        ;;
  restart)
        restart
        ;;
  reload)
        reload
        ;;
  *)
        echo $"Usage: $0 {start|stop|status|restart}"
        exit 2
esac

exit $?

